import { BlobData } from '@/components/BlobsParallaxGroup/BlobsParallaxGroup';

interface BlobElement extends BlobData {
  translateX?: number;
  translateY?: number;
}

export const blobs: BlobElement[] = [
  {
    img: '/blobs/v2.svg',
    left: '-3%',
    top: '42px',
    translateX: 350,
    translateY: -200,
    blur: 80,
    zIndex: -1,
    mouseSensitivity: 3,
    ease: 2,
    baseWidth: 475,
    baseHeight: 634,
  },
  {
    img: '/blobs/v3.svg',
    left: '-7%',
    top: '-410px',
    translateX: 10,
    translateY: -200,
    blur: 80,
    zIndex: -1,
    ease: 1,
    mouseSensitivity: 4,
    baseWidth: 805,
    baseHeight: 713,
  },
  {
    img: '/blobs/v4.svg',
    right: '16.5%',
    top: '-59px',
    baseWidth: 943,
    baseHeight: 643,
    blur: 80,
    ease: 1.5,
    zIndex: -2,
    mouseSensitivity: 3,
  },
  {
    img: '/blobs/v5.svg',
    right: '-16%',
    top: '-100px',
    baseWidth: 801,
    baseHeight: 685,
    mouseSensitivity: 4,
    blur: 80,
    zIndex: -3,
    ease: 2,
  },
  {
    img: '/blobs/v6.svg',
    left: '20%',
    top: '290px',
    baseWidth: 443,
    baseHeight: 599,
    mouseSensitivity: 3,
    blur: 80,
    zIndex: -3,
    ease: 1,
  },
  {
    img: '/blobs/v7.svg',
    right: '23.3%',
    top: '1550px',
    baseWidth: 766,
    baseHeight: 269,
    mouseSensitivity: 4,
    blur: 80,
    zIndex: -1,
    ease: 2,
  },
  {
    img: '/blobs/v8.svg',
    right: '-7%',
    top: '750px',
    baseWidth: 695,
    baseHeight: 432,
    mouseSensitivity: 3,

    blur: 80,
    zIndex: -1,
  },
  {
    img: '/blobs/v9.svg',
    right: '-11.7%',
    top: '1640px',
    baseWidth: 630,
    baseHeight: 429,
    mouseSensitivity: 3.5,

    ease: 2,

    blur: 80,
    zIndex: -1,
  },
  {
    img: '/blobs/v10.svg',
    left: '-0.7%',
    top: '2030px',
    baseWidth: 568,
    baseHeight: 608,
    mouseSensitivity: 4,
    blur: 80,
    zIndex: -1,
    ease: 1,
  },
  {
    img: '/blobs/v11.svg',
    left: '-3%',
    top: '2060px',
    baseWidth: 238,
    baseHeight: 463,
    mouseSensitivity: 3,
    blur: 80,
    ease: 2,
    zIndex: -1,
  },
  {
    img: '/blobs/v12.svg',
    right: '-6.0%',
    top: '2500px',
    baseWidth: 400,
    baseHeight: 391,
    mouseSensitivity: 4,
    blur: 80,
    zIndex: -1,
  },
  {
    img: '/blobs/v13.svg',
    right: '30.7%',
    top: '2630px',
    baseWidth: 791,
    baseHeight: 488,
    mouseSensitivity: 3.4,
    blur: 80,
    zIndex: -1,
  },
  {
    img: '/blobs/v14.svg',
    right: '-30%',
    top: '3180px',
    blur: 80,
    baseWidth: 688,
    baseHeight: 620,
    mouseSensitivity: 3,
    zIndex: -1,
    ease: 1,
  },
  {
    img: '/blobs/v15.svg',
    right: '-13%',
    top: '3490px',
    baseWidth: 675,
    baseHeight: 560,
    mouseSensitivity: 2.5,
    blur: 80,
    zIndex: -2,
    ease: 2,
  },
  {
    img: '/blobs/v16.svg',
    left: '-17%',
    top: '3550px',
    baseWidth: 706,
    baseHeight: 571,
    mouseSensitivity: 4,
    blur: 80,
    zIndex: -1,
    ease: 1,
  },
  {
    img: '/blobs/v17.svg',
    left: '8%',
    top: '4250px',
    baseWidth: 460,
    baseHeight: 567,
    mouseSensitivity: 3.4,
    blur: 80,
    zIndex: -1,
  },
  {
    img: '/blobs/v18.svg',
    top: '4840px',
    left: '-5%',
    blur: 80,
    baseWidth: 747,
    baseHeight: 347,
    mouseSensitivity: 4,
    zIndex: -1,
  },
  {
    img: '/blobs/v19.svg',
    left: '-11%',
    top: '4860px',

    ease: 2,
    baseWidth: 405,
    baseHeight: 406,
    mouseSensitivity: 4,
    blur: 80,
    zIndex: -2,
  },
  {
    img: '/blobs/v20.svg',
    right: '-11%',
    top: '4840px',
    baseWidth: 628,
    baseHeight: 566,
    mouseSensitivity: 3.5,
    blur: 80,
    zIndex: -1,
    ease: 1,
  },
  {
    img: '/blobs/v21.svg',
    left: '-21.5%',
    top: '5480px',
    blur: 80,
    baseWidth: 549,
    baseHeight: 543,
    mouseSensitivity: 4,
    zIndex: -1,
  },
  {
    img: '/blobs/v22.svg',
    right: '8%',
    top: '6280px',
    baseWidth: 493,
    baseHeight: 476,
    mouseSensitivity: 3.6,
    ease: 2,

    blur: 80,
    zIndex: -1,
  },
  {
    img: '/blobs/v23.svg',
    right: '-3.4%',
    top: '6400px',
    baseWidth: 474,
    baseHeight: 564,
    mouseSensitivity: 3,
    blur: 80,

    zIndex: -1,
    ease: 1,
  },
  {
    img: '/blobs/v24.svg',
    left: '-10%',
    top: '6970px',
    baseWidth: 579,
    baseHeight: 530,
    mouseSensitivity: 4,
    blur: 80,
    zIndex: -1,
  },
  {
    img: '/blobs/v25.svg',
    right: '-20%',
    top: '7850px',

    baseWidth: 765,
    baseHeight: 493,
    mouseSensitivity: 3.3,
    blur: 80,
    zIndex: -1,
    ease: 2,
  },
  {
    img: '/blobs/v26.svg',
    left: '-7%',
    top: '7950px',
    blur: 80,
    baseWidth: 508,
    baseHeight: 506,
    mouseSensitivity: 4.3,
    zIndex: -1,
    ease: 1,
  },
];

export const enum NavigationKeys {
  ABOUT = 'about',
  PARTICIPATE = 'participate',
  EVENT = 'event',
  PARTNERS = 'partners',
  APPLY = 'apply',
}

export const flatNavigationItems = [
  { id: NavigationKeys.ABOUT, href: '/' },
  { id: NavigationKeys.PARTICIPATE, href: `#${NavigationKeys.PARTICIPATE}` },
  { id: NavigationKeys.EVENT, href: '/' },
  { id: NavigationKeys.PARTNERS, href: `#${NavigationKeys.PARTNERS}` },
];

export const PHOTO_KEY = 'uploaded_photo';
export const PASSPORT_KEY = 'uploaded_passport';
