name: Deploy Next.js to Github Pages using pnpm

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Cache pnpm
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm install

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0
        with:
          static_site_generator: next

      - name: Set Environment Variables
        run: |
          BASE_PATH="/$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)"
          echo "BASE_PATH=$BASE_PATH" >> .env.local
          echo "BASE_PATH is set to $BASE_PATH"

      - name: Build Next.js
        run: pnpm build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        id: deployment
